config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'recipes/tweet', to: 'homes#tweet_index'
  get 'recipes/tag/:name', to: "recipes#tag_search"
  get 'recipes/search', to: 'recipes#search'

  get 'users/:id/reregistration', to: 'users#reregistration', as: 'reregistration'
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  # URL /users/sign_in ...devise
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # guestログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザー フォロー、フォロワー、お気に入り、材料、退会
  resources :users
  resources :users do
    member do
      get :following, :followers, :favorites, :inventories, :unsubscribe
    end
  end

  # 中間関係
  resources :relationships, only: [:create, :destroy]

  # レシピ コメント、お気に入り
  resources :recipes
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 在庫
  resources :inventories, only: [:show, :new, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :recipe
  belongs_to :user

  has_many :replies, class_name: :Comment, foreign_key: :reply_comment, dependent: :destroy

  validates :content, presence: true, length: { maximum: 100 }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    if comment.save
      if comment.reply_comment.nil?
        flash[:notice] = 'レシピへのコメントを投稿しました。'
      else
        flash[:notice] = 'コメントに返信しました。'
      end
      redirect_to comment.recipe
    else
      if comment.reply_comment.nil?
        flash[:comment] = comment
      end

      flash[:error_messages] = comment.errors.full_messages
      redirect_back fallback_location: comment.recipe
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id], recipe_id: params[:recipe_id]).destroy
    redirect_to comment.recipe
    if comment.reply_comment.nil?
      flash[:notice] = 'コメントを削除しました。'
    else
      flash[:notice] = '返信したコメントを削除しました。'
    end
  end

    private

  def comment_params
    params.require(:comment).permit(:user_id, :recipe_id, :reply_comment, :name, :content)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% comments.each do |comment| %>
  <% if comment.reply_comment.present? || comment.blank? %>
    <% next %>
  <% end %>
  <div class="comment_item">
    <% if user_signed_in? && comment.user == current_user %>
      <%= link_to recipe_comment_path(@recipe.id, comment.id), method: :delete, data: { confirm: '削除してよろしいですか？' } do %>
        <i class="fa-solid fa-trash-can mt-3" style="color: #000000;"></i>  <!--ゴミ箱アイコン-->
      <% end %>
    <% end %>

    <div>
      <%= link_to image_tag(comment.user.avatar.url, class:'comment__img rounded-circle'), user_path(id: comment.user_id) %>
      <%= link_to comment.user.name, user_path(id: comment.user_id) %>
      <div class="post-date"><%= comment.created_at.to_s(:datetime_jp) %></div>
    </div>

    <div><%= comment.content %></div>

    <% if user_signed_in? %>
      <%= render 'comments/reply_form', comment: comment %>
    <% end %>
    <%= render 'comments/reply_comment', comment: comment %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model:[@recipe, @comment], method: :post) do |f| %>
  <%= f.hidden_field :recipe_id, value: @recipe.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :content, "コメント投稿はこちら", class: 'mt-3'%>
  <div class="form-group">
    <%= f.text_area :content, placeholder: "100文字まで入力可能です", class:"form-control introduction" %>
  </div>
  <div class="comment-submit">
    <%= f.button "送信する" , class:"btn btn-outline-primary mb-4" %>
  </div>
<% end %>

app/views/comments/_reply_comment.html.erb
<% comment.replies.order(:created_at).each do |reply| %>
  <div class="comment_reply-item">
    <div>
      <%= link_to image_tag(reply.user.avatar.url, class: 'comment__img rounded-circle'), user_path(id: reply.user_id) %>
      <%= link_to reply.user.name, user_path(id: reply.user_id) %>
    </div>
    <div class="comment_reply-content">
      <%= reply.content %>
      <%= link_to recipe_comment_path(@recipe.id, reply.id), class: 'mr-3', method: :delete, data: { confirm: '削除してよろしいですか？' } do %>
        <i class="fa-solid fa-trash-can" style="color: #000000;"></i>  <!--ゴミ箱アイコン-->
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_reply_form.html.erb
<%= form_with(model: [@recipe, @comment_reply]) do |f| %>
  <%= f.text_field :content, placeholder: "このコメントに返信", class:"form-control introduction" %>
  <%= f.hidden_field :reply_comment, value: comment.id %>
  <%= f.hidden_field :recipe_id, value: @recipe.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="comment_reply-submit">
    <%= button_tag type: "submit", class: "btn btn-default" do %>
      <i class="fa-solid fa-paper-plane" style="color: #000000;"></i>
    <% end %>
  </div>
<% end %>