config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'recipes/tweet', to: 'homes#tweet_index'
  get 'recipes/tag/:name', to: "recipes#tag_search"
  get 'recipes/search', to: 'recipes#search'

  get 'users/:id/reregistration', to: 'users#reregistration', as: 'reregistration'
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  # URL /users/sign_in ...devise
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # guestログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザー フォロー、フォロワー、お気に入り、材料、退会
  resources :users
  resources :users do
    member do
      get :following, :followers, :favorites, :inventories, :unsubscribe
    end
  end

  # 中間関係
  resources :relationships, only: [:create, :destroy]

  # レシピ コメント、お気に入り
  resources :recipes
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 在庫
  resources :inventories, only: [:show, :new, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  default_scope -> { self.order(created_at: :desc) }

  # 材料・作り方関連
  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :ingredients, allow_destroy: true
  accepts_nested_attributes_for :steps, allow_destroy: true

  has_many :comments, dependent: :destroy

  has_many :recipe_tag_relations, dependent: :delete_all, validate: false
  has_many :tags, through: :recipe_tag_relations  #中間テーブルを介してtagモデルと関連付け

  has_many :favorites, dependent: :destroy

  mount_uploader :image, RecipeImageUploader

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50}
  validates :description, presence: true, length: { maximum: 140}

  validate :require_any_ingredients
  validate :require_any_steps

  def require_any_ingredients
    errors.add(:base, "材料は1つ以上登録してください。") if self.ingredients.blank?
  end

  def require_any_steps
    errors.add(:base, "作り方は1つ以上登録してください。") if self.steps.blank?
  end

  before_save do
    if remove_image == true
      self.remove_image!
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "id", "title", "updated_at", "user_id"]
  end

  # 関連タグ表示
  def create_tags(tag_ids)
    tag_ids.shift
    recipe_tag_relations.destroy_all
    tag_ids.each do |tag_id|
      recipe_tag_relations.create!(tag_id: tag_id)
    end
  end

  def self.ransackable_associations(auth_object = nil)
    ["comments", "favorites", "ingredients", "recipe_tag_relations", "steps", "tags", "user"]
  end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]

  def index
    @title = "レシピ一覧"
    # 関連タグ
    @recipes = params[:tag_id].present? ? Tag.find(params[:tag_id]).recipes : Recipe
    if params[:q]
      @q = @recipes.ransack(params[:q])
      search()
    else
      if user_signed_in?
         @recipes = @recipes.includes([:user], [:favorites]).page(params[:page]).per(6)
      else
        @recipes = @recipes.includes([:user]).page(params[:page]).per(6)
      end
    end
  end

  def show
    @title = "#{@recipe.title}"
    @comments = Comment.includes([:user]).where(recipe_id: @recipe.id)
    if user_signed_in?
      @comment = current_user.comments.new(flash[:comment])
      @comment_reply = current_user.comments.new
    end
  end

  def new
    @recipe = Recipe.new(flash[:recipe])
    # 材料追加関連
    @ingredients = @recipe.ingredients.build ##親モデル.子モデル.buildで子モデルのインスタンス作成
    @steps = @recipe.steps.build
  end

  def edit
    @title = "#{@recipe.title}の編集"
    if @recipe.user == current_user
      render "edit"
    else
      redirect_back fallback_location: root_path, flash: { alert: "他人のレシピは編集できません" }
    end
  end

  def create
    recipe = current_user.recipes.new(recipe_params)
    if recipe.save
      recipe.create_tags(params[:recipe][:tag_ids])  # 関連タグ表示
      redirect_to recipe, flash: { notice: "「#{recipe.title}」のレシピを投稿しました。" }
    else
      redirect_to new_recipe_path, flash: {
        recipe: recipe,
        error_messages: recipe.errors.full_messages
      }
    end
  end

  def update
    # binding.irb
    @recipe.update(recipe_params)
    if @recipe.save
      @recipe.create_tags(params[:recipe][:tag_ids])  # 関連タグ表示
      redirect_to @recipe, flash: { notice: "「#{@recipe.title}」のレシピを更新しました。" }
    else
      flash[:recipe] = @recipe
      flash[:error_messages] = @recipe.errors.full_messages
      redirect_back fallback_location: @recipe
    end
  end

  def destroy
    @recipe.destroy
    redirect_to user_path(current_user.id), flash: { notice: "「#{@recipe.title}」のレシピを削除しました。" }
  end

  def search
    if user_signed_in?
      @recipes = @q.result(distinct: true).includes([:favorites]).page(params[:page]).per(6)  # resultにより検索結果を得られる
    else
      @recipes = @q.result(distinct: true).includes([:user]).page(params[:page]).per(6)  # resultにより検索結果を得られる
    end
    @search = params[:q][:title_or_ingredients_content_cont]  # 検索オブジェクト
  end

  def tag_search
    @tag = Tag.find(params[:tag_id])
    @recipes = @tag.recipes.includes([:user], [:favorites])
  end

    private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_q
    @q = Recipe.ransack(params[:q])  #ransack=>gem  検索パラメーターが渡される params[:q]
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(
      :image,
      :image_cache,
      :remove_image,
      :title,
      :description,
      :user_id,
      :keyword,
      tag_ids: [],
      ingredients_attributes: [:id, :content, :quantity, :_destroy],
      steps_attributes: [:id, :direction, :image, :_destroy]
    )
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_favorite.html.erb
<section class="favorite text-right mb-2">
  <% if user_signed_in? %>
    <% if current_user.already_favorited?(recipe) %>  <!--いいね数-->
      <%= link_to recipe_favorites_path(recipe), remote: true, method: :delete do %>
        <i class="fas fa-heart"></i>
      <% end %>
      <span class="mr-2"><%= recipe.favorites.length %></span>
    <% else %>
      <%= link_to recipe_favorites_path(recipe), remote: true, method: :post do %>
        <i class="far fa-heart"></i>
      <% end %>
      <span class="mr-2"><%= recipe.favorites.length %></span>
    <% end %>
  <% end %>

  <%= link_to user_path(id: recipe.user_id) do %>
    <%= image_tag recipe.user.avatar.url, class:'list__user-img rounded-circle' %>  <!--ユーザ画像-->
  <% end %>
  <%= link_to recipe.user.name, user_path(id: recipe.user_id), class: "mr-2" %>  <!--ユーザ名-->
</section>

app/views/recipes/_form.html.erb
<%= render 'shared/flash' %>

<main>
  <%= form_with(model: @recipe, local: true) do |f| %>
    <div class="row my-4">
      <div class="col-md-6 mr-3">
        <%= f.hidden_field :image_cache %>
        <div class="row">
          <div class="col cooking-title">写真</div>
        </div>
        <div class="row mt-1">
          <label class="col-1 img-file pr-0">
            <i class="fa-solid fa-camera pt-2 pr-2" style="color: #000000;"></i>
          </label>
          <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", class: 'col-11 px-1' %>
        </div>
        <div class="description__img">
          <%= image_tag recipe.image.url, class: 'img-fluid' %>
        </div>
        <% unless current_page?(controller:"recipes", action: "new") %>
          <div class="description_remove-img-label">
            <%= f.check_box :remove_image %>
            <%= f.label :remove_image %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 px-sm-0">
        <div class="text-left mt-2 mb-3">
          <h3>レシピについて</h3>
        </div>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "タイトル(50文字以内)", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, placeholder: "サブタイトル(140字以内)", class:"form-control" %>
        </div>
        <div class="cooking-title">材料</div>
        <div class="form-group">
          <%= f.fields_for :ingredients do |ingredient| %>
            <%= render "recipes/ingredient_fields", f: ingredient %>
          <% end %>
          <div id="detail-association-insertion-point"></div>  <!--追加ボタンを押した後、後に代入される--><!--link_to_add_association フォームの追加-->
          <%= link_to_add_association "材料の追加", f, :ingredients,
              class: "btn__color text-white btn btn-block mr-2",
              data: {
              association_insertion_node: '#detail-association-insertion-point',
              association_insertion_method: 'before'
          }%>
        </div>
      </div>
    </div>
    <div class="text-left mt-1 mb-3">
      <h3>関連タグ</h3>
    </div>
    <section class="tag">
      <%# 存在するタグの数だけチェックボックスを追加するメソッドを使用 %>
      <div class="tag__container">
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <%= tag.label class: 'tag__item' do %>
            <%= tag.check_box class: 'tag__checkbox' %>
            <%= tag.text %>
          <% end %>
        <% end %>
      </div>
    </section>
    <div class="text-left mt-3 mb-3">
      <h3>作り方</h3>
    </div>
    <div class="form-group">
      <%= f.fields_for :steps do |step| %>
        <%= render "recipes/step_fields", f: step %>
      <% end %>
      <div id="detail-association-insertion-point_step"></div>  <!--追加ボタンを押した後、後に代入される--><!--link_to_add_association フォームの追加-->
        <%= link_to_add_association "作り方の追加", f, :steps,
            class: "btn__color text-white btn btn-block",
            data: {
              association_insertion_node: '#detail-association-insertion-point_step',
              association_insertion_method: 'before'
        }%>
    </div>
    <div class="row">
      <div class="col-md-10">
        <%= f.submit "送信する", class:"btn btn-outline-success col-md-3 mt-4 mb-4" %>
      </div>
    </div>
  <% end %>
</main>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields mb-2">
  <div class="ingredient_inputBx d-flex">
    <%= f.text_field :content, placeholder: "材料", class:"form-control mr-2"%>
    <%= f.text_field :quantity, placeholder: "分量", class:"form-control" %>
    <%= link_to_remove_association f, class: 'btn btn-default' do %>
      <i class="fa-solid fa-trash-can" style="color: #000000;"></i>
    <% end %>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<span>
  <%= link_to image_tag(recipe.display_image), recipe_path(id: recipe.id) if recipe.image.attached?%>
</span>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields row my-4" style="width: 100% !important; align-items: center">
  <div class="col-md-10 step" style="width: 100%;">
    <%= f.text_area :direction, class:"form-control"%>  <!--手順-->
  </div>

  <div class="col-md-2 mt-2">
    <%= image_tag f.object.image.url, size: "80x80" %>  <!--手順画像-->
    <%= link_to_remove_association f, class: 'btn btn-default' do %>
      <i class="fa-solid fa-trash-can" style="color: #000000;"></i>  <!--ゴミ箱アイコン-->
    <% end %>
  </div>

  <div class="row step_file-input">
    <% if current_page?(controller:"recipes", action: "new") %>
      &emsp;<span class="col-auto step_file-label pt-1 pr-0">手順の画像：</span><%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", id: "step-image", class: "col pl-0" %>
    <% else %>
      &emsp;<span class="col-auto step_file-label pt-1 pr-0">変更後の画像：</span><%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", id: "step-image", class: "col pl-0" %>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <%= render 'form', recipe: @recipe %>
  <div class="row">
    <div class="col-md-10">
      <div class="cancel">
        <%= link_to '編集をやめる', @recipe, class:"btn btn-outline-primary col-md-3 mb-4" %>
      </div>
      <div class="cancel">
        <%= link_to 'レシピを削除', @recipe, method: :delete, data: { confirm: "削除してよろしいですか？" }, class:"btn btn-outline-danger col-md-3 mb-4" %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<%= render 'shared/flash' %>

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 mb-3">
      <h3>レシピ一覧</h3>
    </div>
    <div class="col-md-12 px-sm-0 mt-2">
      <%= render 'shared/recipe_search' %>
      <%= render 'shared/recipe_tag_list' %>
      <%= render 'shared/recipe_list' %>
    </div>
  </div>
  <div class="col-md-12 justify-content-center d-flex mt-4 mb-4">
    <%= paginate @recipes %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <% @title = "レシピ投稿" %>
  <%= render 'form', recipe: @recipe %>
</div>

app/views/recipes/search.html.erb
<div class="cooking-title">
  <% if @search.present? %>
    「<%= @search %>」の検索結果
  <% else %>
    検索結果
  <% end %>
</div>
<%= render 'shared/recipe_search' %>
<%= render 'shared/recipe_list' %>

<div class="col-md-12 justify-content-center d-flex">
  <%= paginate @recipes %>
</div>

<div class="cancel">
  <%= link_to 'レシピ一覧に戻る', recipes_path, class:"btn cancel-btn"%>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/flash' %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-md-6 d-flex justify-content-center">
        <div class="card">
          <%= image_tag @recipe.image.url, class: "description__img" %>
          <div class="card-body">
            <%= @recipe.title %>
            <div class="description_detail">
              <%= @recipe.description %>
            </div>
            <div id="recipe_<%= @recipe.id %>">
              <%= render partial: "favorite", locals: { recipe: @recipe } %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 d-flex justify-content-center align-self-center">
        <div class="recipeuser">
          <div class="text-center mt-4 mb-3">ユーザープロフィール</div>
          <div class="d-flex justify-content-center">
            <%= link_to image_tag(@recipe.user.avatar.url, size: "150x150", class:'rounded-circle'), user_path(id: @recipe.user_id) %>
          </div>
          <%= link_to @recipe.user.name, user_path(id: @recipe.user_id), class:"d-flex justify-content-center mt-3 mb-3" %>
          <div>
            <% if user_signed_in? && @recipe.user == current_user %>
              <%= link_to 'レシピ編集', edit_recipe_path, class:'d-flex justify-content-center mt-4 btn btn-outline-success',data: {"turbolinks"=>false} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="row my-4">
      <div class="col-md-6 my-4">
        <section class="ingredient">
          <div class="cooking-title mb-2">＊材料＊</div>
          <% @recipe.ingredients.each do |ingredient| %>
          <div class="d-flex">
            <div class="ingredient__line col-md-6 mr-2 mb-2" >  <!--ボーダーラインccs-->
              <%= ingredient.content %>
            </div>
            <div class="ingredient__line col-md-6 mb-2" >  <!--ボーダーラインccs-->
              &emsp;<%= ingredient.quantity %>
            </div>
          </div>
          <% end %>
        </section>
      </div>
      <div class="col-md-6 my-4">
        <section class="tag">
          <div class="cooking-title mb-2">＊関連タグ＊</div>
          <div class="ingredient__line mb-2">  <!--ボーダーラインccs-->
            <% if @recipe.tags.empty? %>
              <p class="tag_none">関連タグが設定されていません</p>
            <% else %>
              <% @recipe.tags.each do |tag| %>
                <%= tag.name %>
              <% end %>
            <% end %>
          </div>
        </section>
      </div>
    </div>
    <div class="row my-4">
      <div class="col-md-12 mb-2">＊作り方＊</div>
      <% @recipe.steps.each_with_index do |step, index| %>
        <div class="col-md-12">
          <%= index + 1 %>.
          <p class="ingredient__line form-control" style="height: fit-content;padding: 1%;">
            <%= step.direction %>
          </p>
          <% if step.image? %>
            <%= image_tag step.image.url, class: "stepshow__img mb-2" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= render 'shared/recipe_comment', comments: @comments %>
  </div>
</main>

app/views/recipes/tag_search.html.erb
<section class="list">
  <div class="cooking-title">
    「 <%= @tag.name %> 」の検索結果(<%= @recipes.count %>件)
  </div>
  <%= render 'shared/recipe_list' %>
</section>