config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'recipes/tweet', to: 'homes#tweet_index'
  get 'recipes/tag/:name', to: "recipes#tag_search"
  get 'recipes/search', to: 'recipes#search'

  get 'users/:id/reregistration', to: 'users#reregistration', as: 'reregistration'
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  # URL /users/sign_in ...devise
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # guestログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザー フォロー、フォロワー、お気に入り、材料、退会
  resources :users
  resources :users do
    member do
      get :following, :followers, :favorites, :inventories, :unsubscribe
    end
  end

  # 中間関係
  resources :relationships, only: [:create, :destroy]

  # レシピ コメント、お気に入り
  resources :recipes
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 在庫
  resources :inventories, only: [:show, :new, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController

  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      flash[:alert] = 'ゲストユーザーのパスワード再設定はできません。'
      redirect_to new_user_session_path
    end
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :forbid_guest_user, {only: [:edit, :update, :destroy]}

  # GET /resource/sign_up
  def new
    super
    @user = User.new
  end

  # POST /resource
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     flash[:notice] = "ユーザー認証メールを送信いたしました。認証が完了しましたらログインをお願いいたします。"
  #     redirect_to new_user_session_path
  #   else
  #     flash[:alert] = "ユーザー登録に失敗しました。"
  #     render action: :new and return
  #   end
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました。"
      redirect_to new_user_session_path
    else
      flash[:alert] = "ユーザー更新に失敗しました。"
      render action: :edit and return
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

    # アカウント編集後、プロフィール画面に移動する
    def after_update_path_for(resource)
      user_path(id: current_user.id)
    end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end

    def forbid_guest_user
      if @user.email == "guest@example.com"
        flash[:alert] = "ゲストユーザーの編集・退会はできません。"
        redirect_to root_path
      end
    end

    def update_resource(resource, params)
      resource.update_without_current_password(params)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, flash: { notice: 'ゲストユーザーとしてログインしました。' }
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   p "来てる"
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:index, :destroy, :inventories]
  before_action :set_user, except: [:index, :restore_mail, :restoration]
  before_action :withdrawal_forbid_guest_user, only: [:unsubscribe, :withdrawal]
  before_action :withdrawal_forbit_other_user, only: [:unsubscribe, :withdrawal]



  def index
    @users = User.includes(:recipes).where(is_deleted: false).page(params[:page]).per(6).order(id: :ASC)
  end

  def show
    @title = "#{current_user.name}さんのページ"
    if user_signed_in?
      @recipes = User.find(params[:id]).recipes.includes([:favorites]).page(params[:page]).per(6)
    else
      @recipes = User.find(params[:id]).recipes.page(params[:page]).per(6)
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, success: "「#{@user.name}を削除しました」"
  end

  def following
    @title = "#{@user.name}さんがフォロー中"
    @message = "まだ誰もフォローしていません。"
    @users = @user.following.includes(:recipes).page(params[:page]).per(6)
    render 'show_follow'
  end

  def followers
    @title = "#{@user.name}さんのフォロワー"
    @message = "まだ誰からもフォローされていません。"
    @users = @user.followers.includes(:recipes).page(params[:page]).per(6)
    render 'show_follow'
  end

  def favorites
    @title = "#{@user.name}さんがいいねしたレシピ"
    @recipes = @user.favorite_recipes.includes([:user], [:favorites]).page(params[:page]).per(6)
    render 'show_favorite'
  end

  def inventories
    if user_signed_in? && @user.id == current_user.id
      @title = "食材管理"
      @inventories = @user.inventories.page(params[:page]).order(expiration_date: 'ASC').per(6)
      render 'show_inventory'
    else
      flash[:alert] = "他人の食材管理ページ閲覧及び編集はできません。"
      redirect_to root_path
    end
  end

  def withdrawal
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理が完了しました。"
    redirect_to new_user_session_path
  end


    private

  def set_user
    @user = User.find(params[:id])
  end

  def withdrawal_forbid_guest_user
    if @user.email == "guest@example.com"
      flash[:alert] = "ゲストユーザーの退会処理はできません。"
      redirect_to root_path
    end
  end

  def withdrawal_forbit_other_user
    if current_user.email != @user.email
      flash[:alert] = "他の方の退会処理はできません。"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "フォロー", class: 'btn btn-outline-success' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless  user_signed_in? && @user == current_user %>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
<% end %>

app/views/users/_show_user.html.erb
<div class="row mt-5 mb-4">
  <div class="col-md-6 text-center" style="align-items: center">
    <%= image_tag user.avatar.url, class: "rounded-circle mb-2", size: "150x150" %>
    <div class="user_name"><%= user.name %></div>
    <div class="d-flex flex-row justify-content-center mb-4">
      <%= link_to(following_user_path(user), class:'user__follow') do %>
        <div class="d-flex flex-row mr-4">
          <p class="mr-1">フォロー</p>
          <%= user.following.length %>
        </div>
      <% end %>
      <%= link_to(followers_user_path(user), class:'user__follow') do %>
        <div class="d-flex flex-row">
          <p class="mr-1">フォロワー</p>
          <%= user.followers.length %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-6 d-flex justify-content-center" style="align-items: center">
    <div class="user__follow-submit">
      <%= render 'shared/user_submenu' if user == current_user %>
      <div id="follow_form">
        <%= render 'follow_form' if user_signed_in? %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <%= render 'shared/stats' %>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-danger"%>
<% end %>

app/views/users/index.html.erb
<% @title = "ユーザ一覧" %>

<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 mb-3">
      <h3>ユーザ一覧</h3>
    </div>
    <%= render 'shared/user-list' %>
  </div>
  <div class="col-md-12 justify-content-center d-flex mb-4">
    <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <section class="user">
    <%= render 'shared/flash' %>
    <%= render 'show_user', user: @user %>
  </section>
  <section class="list">
    <div class="main-title mt-4 mb-4">
      <h3>Recipe</h3>
    </div>
    <% if @recipes.any? %>
      <%= render 'shared/recipe_list' %>
    <% else %>
      <p class="notthing"><%= "#{@user.name}さんの投稿はありません。" %></p>
    <% end %>
    <div class="col-md-12 justify-content-center d-flex mb-4">
      <%= paginate @recipes %>
    </div>
  </section>
</div>

app/views/users/show_favorite.html.erb
<div class="container">
  <section class="user">
    <%= render 'show_user', user: @user %>
  </section>
  <%= render 'shared/flash' %>
  <section class="user-list">
    <div class="subheader">
      <div class="main-title mt-4 mb-4">
        <h3>Favorite</h3>
      </div>
    </div>
    <% if @recipes.any? %>
      <%= render 'shared/recipe_list' %>
    <% else %>
      <p class="notthing"><%= "#{@user.name}さんがいいねしたレシピはありません。" %></p>
    <% end %>
    <div class="col-md-12 justify-content-center d-flex mb-4">
      <%= paginate @recipes %>
    </div>
  </section>
</div>

app/views/users/show_follow.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 mb-3">
      <h3><%= @title %></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 mb-4">
      <% if @users.any? %>
        <%= render 'shared/user-list' %>
      <% else %>
        <p class="notthing"><%= @message %></p>
      <% end %>
      <div class="col-md-12 justify-content-center d-flex mb-4">
        <%= paginate @users %>
      </div>

      <%= link_to "マイページに戻る", @user, class: "btn btn-outline-primary mb-4" %>
    </div>
  </div>
</div>

app/views/users/show_inventory.html.erb
<div class="container">
  <section class="user">
    <%= render 'show_user', user: @user %>
  </section>
  <%= render 'shared/flash' %>
  <section class="user-list">
    <div class="container">
      <div class="main-title mt-4 mb-4">
        <h3>Inventory</h3>
      </div>
    </div>
    <% if @inventories.any? %>
      <%= render 'shared/food_inventory' %>
    <% else %>
      <p class="notthing"><%= "保存中の食材はありません。" %></p>
    <% end %>
    <div class="col-md-12 justify-content-center d-flex">
      <%= paginate @inventories %>
    </div>
    <div class="container mt-5 mb-3">
      <%= link_to "食材を登録", new_inventory_path, class: "btn btn-outline-success mt-3" %>
    </div>
  </section>
</div>

app/views/users/unsubscribe.html.erb
<div class="row login__background">
  <div class="col-md-6 px-sm-0 d-flex">
    <%= image_tag 'introduction.jpg', class: "introduction__img" %>
  </div>
  <div class="col-md-6 align-self-center">
    <div class="col-md-10 offset-md-1">
      <div class="text-center mt-4 mb-4">
        <h3>退会お手続き</h3>
      </div>
      <p class="text-center">
        退会手続きをされますと<br>
        一部サービスがご利用いただけなくなります。<br>
        <br>
        本当に退会してよろしいですか？
      </p>
      <div class="col-md-12 px-sm-0 d-flex justify-content-center">
        <%= link_to "退会しない", user_path(current_user), class: 'btn btn-outline-primary mt-3 mb-4' %>
        <%= link_to "退会する", withdrawal_path, method: :patch, data: { confirm: "本当に退会しますか？" }, class: "btn btn-outline-danger ml-5 mt-3 mb-4" %>
      </div>
    </div>
  </div>
</div>