config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'recipes/tweet', to: 'homes#tweet_index'
  get 'recipes/tag/:name', to: "recipes#tag_search"
  get 'recipes/search', to: 'recipes#search'

  get 'users/:id/reregistration', to: 'users#reregistration', as: 'reregistration'
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  # URL /users/sign_in ...devise
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # guestログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # ユーザー フォロー、フォロワー、お気に入り、材料、退会
  resources :users
  resources :users do
    member do
      get :following, :followers, :favorites, :inventories, :unsubscribe
    end
  end

  # 中間関係
  resources :relationships, only: [:create, :destroy]

  # レシピ コメント、お気に入り
  resources :recipes
  resources :recipes do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  # 在庫
  resources :inventories, only: [:show, :new, :create, :edit, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% flash[:error_messages].each do |msg| %>
  <div class="alert">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<!-- 投稿完了後のフラッシュメッセージ -->
<% if flash[:error_messages] %>
  <%= render 'shared/error_messages' %>
<% else %>
  <%= render 'layouts/notifications' %>
<% end %>

app/views/shared/_food_inventory.html.erb
<div class="container">
  <div class="row">
    <% @inventories.each do |inventory| %>
      <div class="col-md-3 mb-2">
        <div class="card">
          <div class="justify-content-center">
            <%= link_to image_tag(inventory.image.url, class: "inventory__photo"), inventory_path(inventory.id) %>  <!--食材画像-->
          </div>
          <div class="card-body">
            <%= link_to inventory.name, inventory_path(inventory.id) %>  <!--食材名-->
            <div class="inventory_content d-flex">
              <span class="inventory_count mr-4"><%= inventory.days_left %></span>  <!--賞味期限までの日数-->
              <div class="inventory_quantity mr-4">
                <span class="inventory_count"><%= inventory.quantity %>個</span>  <!--在庫数-->
              </div>
              <%= link_to inventory_path(id: inventory.id), method: :delete, data: { confirm: '削除してよろしいですか？' } do %>
                <i class="fa-solid fa-trash-can" style="color: #000000;"></i>  <!--ゴミ箱-->
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="text-white", style="background-color: #FFA500; height: 120px; text-align: center; line-height: 120px;">
    <div class="mx-auto">
      <%= link_to root_path do %>
        <%= image_tag 'EnjoyRecipe2.png', size: "100x100" %>
      <% end %>
      &copy; 2023 Yumi.Teramoto.
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- headerの記述 -->
<header>
  <div class="header" style="z-index:1;">  <!--styleでheaderの前面・後面を指定できる 2か所に記述-->
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to root_path do %>
        <%= image_tag 'EnjoyRecipe.png', size: "100x100" %>  <!--logo-->
      <% end %>

      <!--ハンバーガーメニュー-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <% if user_signed_in? %>
          <ul class="navbar-nav ml-auto">
            <div class="text-end mr-2">
              <%= link_to 'マイページ', user_path(id: current_user.id), class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
            <div class="text-end mr-2">
              <%= link_to 'タイムライン', recipes_tweet_path, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
            <div class="text-end mr-2">
              <%= link_to 'レシピ一覧', recipes_path, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
            <div class="text-end mr-2">
              <%= link_to 'ユーザ一覧', users_path, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
            <div class="text-end mr-2">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
          </ul>
        <% else %>
          <ul class="navbar-nav">
            <div class="text-end mr-2">
              <%= link_to '新規登録', new_user_registration_path, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
            <div class="text-end mr-2">
              <%= link_to 'ログイン', new_user_session_path, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
            <div class="text-end mr-2">
              <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
            <div class="text-end mr-2">
              <%= link_to 'レシピ一覧', recipes_path, class:"btn btn-warning text-white w-100 mb-2" %>
            </div>
          </ul>
        <% end %>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_recipe_comment.html.erb
<section class="comment">
  <div class="comment_count">
    コメント<%= comments.where(reply_comment: nil).length %>件
  </div>
  <%= render "comments/comment", comments: comments %>
  <% if user_signed_in? %>
    <div class="comment_form">
      <%= render 'comments/form' %>
    </div>
  <% end %>
</section>

app/views/shared/_recipe_list.html.erb
<div class="row">
  <% @recipes.each do |recipe| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <%= link_to image_tag(recipe.image.url,class:"list__img mr-2"), recipe_path(recipe) %>  <!--レシピ画像-->
        <div class="card-body">
          <span class="timestamp"><%= recipe.created_at.to_s(:datetime_jp) %></span><br>  <!--日付-->
          <%= link_to recipe.title, recipe_path(recipe) %>  <!--タイトル-->
          <div class="list_description"><%= recipe.description %></div>  <!--サブタイトル-->
        </div>
        <div class="list_info">
          <div id="recipe_<%= recipe.id %>">
            <%= render partial: "recipes/favorite", locals: { recipe: recipe } %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_recipe_search.html.erb
<form>
  <div class="row">
    <div class="col-md-12 mt-4 mb-2">
      <%= search_form_for @q, url: recipes_search_path do |f| %>
        <%= f.search_field :title_or_ingredients_content_cont, placeholder: "レシピ名・食材名で検索", class:"form-control" %>
      <% end %>
    </div>
  </div>
</form>

app/views/shared/_recipe_tag_list.html.erb
<form>
  <%= form_tag recipes_path do %>
      <%= select_tag :tag_id,
                      options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                      {
                        prompt: 'タグで絞り込み',
                        class: 'tag__item mt-2 mb-5 rounded-lg',
                        style: "opacity: 0.6; padding: 6px;",
                        onchange: 'submit(this.form);'
                      }
      %>
  <% end %>
</form>

app/views/shared/_stats.html.erb
<div class="col-md-4 justify-content-center d-flex mypage__botton">
  <%= link_to(user_path(@user)) do %>
    <div class="d-flex flex-col">
      <p class="mr-1">レシピ</p>
      <%= @user.recipes.length %>
    </div>
  <% end %>
</div>
<div class="col-md-4 justify-content-center d-flex mypage__botton">
  <%= link_to(favorites_user_path(@user)) do %>
    <div class="d-flex flex-col">
      <p class="mr-1">いいね</p>
      <p class="user_count" id="following"><%= @user.favorites.length %></p>
    </div>
  <% end %>
</div>
<div class="col-md-4 justify-content-center d-flex mypage__botton">
  <% if @user == current_user %>
    <%= link_to(inventories_user_path(@user)) do %>
      <div class="d-flex flex-col">
        <p class="mr-1">食材</p>
        <p class="user_count"><%= @user.inventories.length %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_user-list.html.erb
<% @users.each do |user| %>
  <div class="col-md-6 mb-4">
    <%= link_to(user_path(id: user.id)) do %>
      <div class="card">
        <div class="recipelist__flex">
          <%= image_tag user.avatar.url, class:'rounded-circle mt-3 mb-3 ml-3', size:"100x100" %>  <!--ユーザー画像-->
          <div class="card-body">
            <div class="user-list_detail">
              <div class="user-list_name">
                <%= user.name %>  <!--ユーザー名-->
              </div>
              <div class="user-list_count">
                レシピ投稿数: <%= user.recipes.length %>  <!--レシピ投稿数-->
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_user_submenu.erb
<% if @user == current_user %>
  <div class="d-flex justify-content-center mt-2 mb-2">
    <%= link_to 'レシピ投稿', new_recipe_path, class:'btn btn-outline-success w-100',data: {"turbolinks"=>false} %>
  </div>
  <div class="d-flex justify-content-center mb-2">
    <%= link_to 'ユーザー編集', edit_user_registration_path, class:'btn btn-outline-secondary' %>
  </div>
<% end %>